### PR TITLE
Deleted conflicting library code.

### PR DESCRIPTION
**Pull request by Manabarb**
Please leave feedback if any.
image

### CODE REVIEW

**Comment by Owain94** [comment]
Why are these deleted exactly?

**Comment by Manabarb** [comment]
They end up in an error that people have asked about on the discord, 
Question

This way wiki readers can use the example to start their own plugin by just adding it to the plugin project.

**Comment by Owain94** [comment]
Isn't that an user error? Because they're copy pasting the whole 'javaexample' folder without fixing up their build scripts?
I believe this change will break the example plugin when just using this repo as a base.

**Comment by Manabarb** [comment]
Well, considering it's an example and the main plugin repo is not compatible by default while all other plugins are, is it a good example?
I will test the repo and see if there are any problems.

**Comment by Owain94** [comment]
Yes it is, it doesn't really matter that this repo is not compatible with the OpenOSRS plugins repo, they are two complete different things anyways.

This example repo can be a base for anyone their own plugin repo and it includes the bootstrapping logic to release the plugins to the public as well.

There are quite a bunch of developers that have based their own repos off of this one and changing the build scripts in a way that completely breaks the compiling of these examples for the sole reason that it's easier to copy and paste them into a completely unrelated repository is not great imo.

**Pull request closed without merging**
